core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name='index_view'),
    path('login/', login_view, name='login_view'),
    path('logout/', logout_view, name='logout_view'),
    path('imobiliaria/', include('imobiliaria.urls')),
    path('locador/', include('locador.urls')),
    path('locatario/', include('locatario.urls')),
    path('pagamento/', include('pagamento.urls')),
]

locador/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('auto_cadastro/', cadastro_view, name='auto_cadastro_locador_view'),
    path('home/', home_view, name='home_locador_view'),
    path('meus_imoveis/', meus_imoveis_view, name='imoveis_locador_view'),
    path('meus_imoveis/novo/', cadastro_imovel_view, name='cadastro_imovel_view'),
    path('meus_imoveis/<int:id>/', ler_imovel_view, name='ler_imovel_view'),
    path('meus_imoveis/atualizar/<int:id>/', atualizar_imovel_view, name='atualizar_imovel_view'),
    path('meus_imoveis/deletar/<int:id>/', deletar_imovel_view, name='deletar_imovel_view'),
    path('meus_inquilinos/', meus_inquilinos_view, name='inquilinos_locador_view'),
    path('meus_inquilinos/<int:id>/', ler_inquilino_view, name='ler_inquilino_view'),
    path('meus_inquilinos/adicionar_ao_imovel/<str:tipo><int:id>', inquilino_ao_imovel_view, name='inquilino_ao_imovel_view'),
    path('meus_inquilinos/remover_do_imovel/<str:tipo><int:id>', remover_inquilino_do_imovel_view, name='remover_inquilino_do_imovel_view'),
    path('configuracoes/', configuracoes_view, name='configuracoes_locador_view'),
    path('configuracoes/alterar_senha/', alterar_senha_view, name='alterar_senha_view'),
    path('configuracoes/informacoes_da_conta/', alterar_informacoes_da_conta_view, name='alterar_informacoes_da_conta_view'),
    path('devedores/', devedores_view, name='devedores_view'),
    path('pagamentos_locador/', pagamentos_locador_view, name='pagamentos_locador_view')
]

locador/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from datetime import date, datetime
import calendar
from django.db.models import Q


class Locador(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    data_nascimento_criacao = models.DateField()
    ultimo_pagamento = models.DateField(null=True, blank=True)
    telefone = models.CharField(null=True, blank=True, max_length=20)

    def __str__(self) -> str:
        if self.usuario:
            return f'{self.id} - {self.usuario.username} - {self.usuario.first_name}'
        else:
            return f'SEM USUARIO'
        
    def get_devedores(self, mes_referencia=None):
        from locatario.models import Locatario
        from pagamento.models import PagamentoImovel

        if not mes_referencia:
            mes_referencia = timezone.now().date()
        else:
            mes_referencia = datetime.strptime(mes_referencia, '%Y-%m').date()
        
        devedores = []
        inquilinos = Locatario.objects.filter(locador=self, imovel__isnull=False)
        
        for inquilino in inquilinos:
            inicio_mes = date(mes_referencia.year, mes_referencia.month, 1)
            fim_mes = date(mes_referencia.year, mes_referencia.month, calendar.monthrange(mes_referencia.year, mes_referencia.month)[1])
            pagamento_deste_mes = PagamentoImovel.objects.filter(locatario=inquilino).filter(Q(data__gte=inicio_mes, data__lte=fim_mes)).first()
            if pagamento_deste_mes:
                devedores.append(pagamento_deste_mes)
            else:
                devedores.append(PagamentoImovel(locatario=inquilino, imovel=inquilino.imovel, valor=0.0, status='N'))
            mes_referencia = mes_referencia + relativedelta(months=1)
        
        return devedores

imovel/forms.py
from django import forms
from .models import *
from locatario.models import Locatario
from django.utils import timezone

class ImovelCreationForm(forms.ModelForm):
    nome = forms.CharField(label='Nome/Identificação do imóvel', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do imóvel'}))
    cep = forms.CharField(label='CEP', max_length=9, label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'CEP'}))
    numero = forms.CharField(label='Número', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número'}))
    endereco = forms.CharField(label='Endereço', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Endereço'}))
    bairro = forms.CharField(label='Bairro', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bairro'}))
    cidade = forms.CharField(label='Cidade', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Cidade'}))
    uf = forms.CharField(label='UF', label_suffix=' *', max_length=2, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'UF'}))
    mensalidade = forms.CharField(label='Mensalidade', max_length=13, label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Mensalidade'}))
    class Meta:
        model = Imovel
        fields = ('nome', 'cep', 'numero', 'endereco', 'bairro', 'cidade', 'uf', 'mensalidade')

class ImovelUpdateForm(forms.ModelForm):
    nome = forms.CharField(label='Nome/Identificação do imóvel', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do imóvel'}))
    cep = forms.CharField(label='CEP', max_length=9, label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'CEP'}))
    numero = forms.CharField(label='Número', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número'}))
    endereco = forms.CharField(label='Endereço', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Endereço'}))
    bairro = forms.CharField(label='Bairro', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bairro'}))
    cidade = forms.CharField(label='Cidade', label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Cidade'}))
    uf = forms.CharField(label='UF', label_suffix=' *', max_length=2, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'UF'}))
    mensalidade = forms.CharField(label='Mensalidade', max_length=13, label_suffix=' *', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Mensalidade'}))
    DISPONIVEL_CHOICES = [(True, 'Disponível'), (False, 'Indisponível')]
    disponivel = forms.ChoiceField(choices=DISPONIVEL_CHOICES, label='Disponível', label_suffix='', widget=forms.Select(attrs={'class':'form-control', 'placeholder': 'Disponível'}))
    class Meta:
        model = Imovel
        fields = '__all__'
        exclude = ('locador',)

class LocatarioAoImovelForm(forms.Form):
    imovel = forms.ModelChoiceField(queryset=Imovel.objects.filter(disponivel=True), label='Imóvel', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Imóvel'}))
    locatario = forms.ModelChoiceField(queryset=Locatario.objects.filter(imovel__isnull = True), label='Inquilino', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Inquilino'}))

    def save(self):
        imovel = self.cleaned_data['imovel']
        locatario = self.cleaned_data['locatario']
        imovel.disponivel = False
        locatario.imovel = imovel
        locatario.data_entrada_imovel = timezone.now()
        imovel.save()
        locatario.save()

locador/forms.py
from django import forms
from .models import Locador
from django.contrib.auth.models import User

class LocadorCreationForm(forms.ModelForm):
    data_nascimento_criacao = forms.DateField(label='Data de nascimento ou criação da empresa', label_suffix=' *', widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control', 'placeholder': 'Data de nascimento ou criação da empresa'}))

    class Meta:
        model = Locador
        fields = '__all__'
        exclude = ('usuario', 'ultimo_pagamento', 'telefone')

    def save(self, user:User, commit: bool = ...):
        user.save()
        locador = Locador.objects.create(usuario=user, data_nascimento_criacao=self['data_nascimento_criacao'].value())
        return locador
    
class LocadorUpdateForm(forms.ModelForm):
    telefone = forms.CharField(label='Telefone para contato', label_suffix='', required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone para contato'}))
    data_nascimento_criacao = forms.DateField(label='Data de nascimento ou criação da empresa', label_suffix=' *', required=False, widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control', 'placeholder': 'Data de nascimento ou criação da empresa'}))
    
    class Meta:
        model = Locador
        fields = '__all__'
        exclude = ('usuario', 'ultimo_pagamento',)

    def save(self, commit: bool = ...):
        return super().save(commit)

locador/views.py
from django.shortcuts import render, redirect
from .forms import *
from imobiliaria.forms import *
from imovel.models import Imovel
from locador.models import Locador
from django.contrib.auth.decorators import login_required
from imovel.forms import *
from django.shortcuts import get_object_or_404
from locatario.models import Locatario
from django.db.models import Q
from django.contrib import messages
from pagamento.models import PagamentoImovel, PagamentoAssinatura


def cadastro_view(request):
    context = {}
    if request.method == 'GET':
        form1 = CustomUserCreationForm()
        form2 = LocadorCreationForm()
    elif request.method == 'POST':
        form1 = CustomUserCreationForm(request.POST)
        form2 = LocadorCreationForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            user = form1.save(commit=False)
            form2.save(user)
            print('redirecionar locador para a pagina de pagamento')
            # return redirect('locador_pagamento_view')
    context['form1'] = form1
    context['form2'] = form2
    return render(request, 'views/cadastro_locador.html', context)


@login_required
def home_view(request):
    context = {}
    locador = Locador.objects.get(usuario=request.user)

    context['locador'] = locador
    return render(request, 'views/home_locador.html', context)


@login_required
def meus_imoveis_view(request):
    context = {}

    order_by = request.GET.get('order_by', 'id')
    direction = request.GET.get('direction', 'id')

    locador = Locador.objects.get(usuario=request.user)
    imoveis = Imovel.objects.filter(locador=locador).order_by(order_by)
    if request.method == 'GET':
        if request.GET.get('busca'):
            busca = request.GET.get('busca')
            imoveis = Imovel.objects.filter(locador=locador).order_by('disponivel')
            imoveis = imoveis.filter(Q(nome__icontains=busca) | Q(endereco__icontains=busca))

    context['order_by'] = order_by
    context['direction'] = direction
    context['imoveis'] = imoveis
    return render(request, 'views/imoveis_locador.html', context)


@login_required
def cadastro_imovel_view(request):
    form = ImovelCreationForm()

    if request.method == 'POST':
        form = ImovelCreationForm(request.POST)
        if form.is_valid():
            imovel = form.save(commit=False)
            locador = Locador.objects.get(usuario=request.user)
            imovel.locador = locador
            imovel.save()
            return redirect('imoveis_locador_view')

    return render(request, 'views/cadastro_imovel.html', {'form': form})


@login_required
def atualizar_imovel_view(request, id):
    context = {}

    locador = Locador.objects.get(usuario=request.user)
    imovel = get_object_or_404(Imovel, pk=id)

    if imovel.locador != locador:
        redirect('imoveis_locador_view')

    form = ImovelUpdateForm(instance=imovel)
    if request.method == 'POST':
        form = ImovelUpdateForm(request.POST, instance=imovel)
        if form.is_valid():
            form.save()
            return redirect('imoveis_locador_view')

    context['form'] = form
    context['imovel'] = True
    return render(request, 'views/cadastro_imovel.html', context)


@login_required
def remover_inquilino_do_imovel_view(request, tipo, id):
    if tipo == 'imovel':
        imovel = get_object_or_404(Imovel, pk=id)
        inquilino = get_object_or_404(Locatario, imovel=imovel)
    else:
        inquilino = get_object_or_404(Locatario, pk=id)
        imovel = inquilino.imovel

    imovel.disponivel = True
    inquilino.imovel = None
    inquilino.data_entrada_imovel = None
    imovel.save()
    inquilino.save()
    return redirect('imoveis_locador_view')


@login_required
def deletar_imovel_view(request, id):
    locador = Locador.objects.get(usuario=request.user)
    imovel = get_object_or_404(Imovel, pk=id)
    if imovel.locador != locador:
        redirect('imoveis_locador_view')
    imovel.delete()
    return redirect('imoveis_locador_view')


@login_required
def meus_inquilinos_view(request):
    context = {}

    order_by = request.GET.get('order_by', 'id')

    locador = Locador.objects.get(usuario=request.user)
    locatarios = Locatario.objects.filter(locador=locador).order_by(order_by)

    if request.method == 'GET':
        if request.GET.get('busca'):
            busca = request.GET.get('busca')
            locatarios = locatarios.filter(Q(usuario__first_name__icontains=busca) | Q(usuario__last_name__icontains=busca) | Q(imovel_nome__icontains=busca))

    context['inquilinos'] = locatarios
    context['order_by'] = order_by
    context['meu_id'] = locador.id
    return render(request, 'views/inquilinos_locador.html', context)


@login_required
def inquilino_ao_imovel_view(request, tipo, id):
    if tipo == 'imovel':
        form = LocatarioAoImovelForm(
            initial={'imovel': Imovel.objects.get(pk=id)})
    else:
        form = LocatarioAoImovelForm(
            initial={'locatario': Locatario.objects.get(pk=id)})

    if request.method == 'POST':
        form = LocatarioAoImovelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('imoveis_locador_view')

    return render(request, 'views/inquilino_ao_imovel.html', {'form': form})


@login_required
def ler_inquilino_view(request, id):
    locador = Locador.objects.get(usuario=request.user)
    inquilino = get_object_or_404(Locatario, pk=id)

    if inquilino.locador != locador:
        return redirect('inquilinos_locador_view')
    
    return render(request, 'views/ler_inquilino.html', {'inquilino': inquilino})


@login_required
def ler_imovel_view(request, id):
    locador = Locador.objects.get(usuario=request.user)
    imovel = get_object_or_404(Imovel, pk=id)

    if imovel.locador != locador:
        return redirect('imoveis_locador_view')
    
    return render(request, 'views/ler_imovel.html', {'imovel': imovel})


@login_required
def configuracoes_view(request):
    return render(request, 'views/configuracoes.html')


@login_required
def alterar_senha_view(request):
    context = {}
    form = UpdatePasswordForm(user=request.user)
    if request.method == 'POST':
        form = UpdatePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('logout_view')
    context['form'] = form
    return render(request, 'views/configuracoes/senha.html', context)


@login_required
def alterar_informacoes_da_conta_view(request):
    context = {}

    user = request.user
    locador = Locador.objects.get(usuario=user)
    locador.data_nascimento_criacao = locador.data_nascimento_criacao.strftime("%Y-%m-%d")
    
    form1 = CustomUpdateUserForm(instance=user)
    form2 = LocadorUpdateForm(instance=locador)

    if request.method == 'POST':
        form1 = CustomUpdateUserForm(instance=user, data=request.POST)
        form2 = LocadorUpdateForm(instance=locador, data=request.POST)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            messages.success(request, 'Dados atualizados com sucesso!')

    context['form1'] = form1
    context['form2'] = form2
    return render(request, 'views/configuracoes/conta.html', context)


@login_required
def devedores_view(request):
    context = {}
    locador = Locador.objects.get(usuario=request.user)
    
    mes_referencia = request.GET.get('mes_referencia')
    pagamentos = locador.get_devedores(mes_referencia)
    
    context['pagamentos'] = pagamentos
    context['mes_referencia'] = mes_referencia
    return render(request, 'views/devedores.html', context)


def pagamentos_locador_view(request):
    context = {}
    locador = Locador.objects.get(usuario=request.user)
    pagamentos_locador = PagamentoAssinatura.objects.filter(locador=locador)
    pagamentos_inquilinos = PagamentoImovel.objects.filter(locatario__locador=locador)

    context['pagamentos_locador'] = pagamentos_locador
    context['pagamentos_inquilinos'] = pagamentos_inquilinos
    return render(request, 'views/pagamentos_locador.html', context)

locador/templates/views/cadastro_imovel.html
{% extends 'base_locador.html' %}
{% block base_locador %}

<div class="col-sm-12 col-lg-6 offset-lg-3">
    <form method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-header text-center">
                <h5>{{ imovel|yesno:"Atualizar imovel,Novo imovel"}}</h5>
            </div>
            <div class="card-body">
                {% for field in form %}
                    <div class="form-floating mb-3">
                        {{field}}
                        {{field.label_tag}}
                        <span class="text-danger">{{field.errors.0}}</span>
                    </div>
                {% endfor%}
            </div>    
            <div class="card-footer text-end">
                <a class="btn btn-light" href="{% url 'imoveis_locador_view' %}">Cancelar</a>
                <button type="submit" class="btn btn-orange">Salvar</button>
            </div>
        </div>
    </form>
</div>



<script>
    $('#id_cep').mask('00000-000')
    $('#id_mensalidade').mask('##0.000,00', {reverse: true})

    $("#id_cep").blur(function(){
        pesquisacep(this.value)
    });

    function limpa_formulário_cep() {
        //Limpa valores do formulário de cep.
        document.getElementById('id_endereco').value = ("");
        document.getElementById('id_bairro').value = ("");
        document.getElementById('id_cidade').value = ("");
        document.getElementById('id_uf').value = ("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('id_endereco').value = (conteudo.logradouro);
            document.getElementById('id_bairro').value = (conteudo.bairro);
            document.getElementById('id_cidade').value = (conteudo.localidade);
            document.getElementById('id_uf').value = (conteudo.uf);
        } //end if.
        else {
            //CEP não Encontrado.
            limpa_formulário_cep();
            alert("CEP não encontrado.");
        }
    }

    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if (validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('id_endereco').value = "...";
                document.getElementById('id_bairro').value = "...";
                document.getElementById('id_cidade').value = "...";
                document.getElementById('id_uf').value = "...";

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = 'https://viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
                limpa_formulário_cep();
                alert("Formato de CEP inválido.");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

</script>

{% endblock %}

locador/templates/views/cadastro_locador.html
{% extends 'register.html' %}
{% load static %}
{% block register %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="col-sm-12 col-lg-6">
    <h4 class="mb-3 text-orange">Cadastre seus dados</h4>
    <form method="POST" autocomplete="off">
        {% csrf_token %}

        {% for field in form1 %}
            <div class="form-floating mb-3">
                {{field}}
                {{field.label_tag}}
                <span class="text-danger">{{field.errors.0}}</span>
            </div>
        {% endfor%}

        {% for field in form2 %}
            <div class="form-floating mb-3">
                {{field}}
                {{field.label_tag}}
                <span class="text-danger">{{field.errors.0}}</span>
            </div>
        {% endfor%}
        
        <div class="d-grid gap-2">
            <button type="submit" class="btn btn-orange btn-block py-2 fw-bold fs-5">Cadastrar</button>
        </div>
    </form>
</div>

<script>
    $('#id_username').on('input', function(){
        if($(this).val().length <= 11){
            $(this).next('label').text('CPF')
        }else{
            $(this).next('label').text('CNPJ')
        }
    })
    $('#id_username').mask('00000000000000')
    $('#id_telefone').mask('(00) 0 0000-0000')
</script>

{% endblock %}

locador/templates/views/configuracoes.html
{% extends 'base_locador.html' %}
{% block base_locador %}

<div class="col-sm-12 col-lg-6 offset-lg-3">
    <div class="card">
        <div class="card-header">
            <h5>Configurações</h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><a class="text-dark" href="{%url 'alterar_senha_view'%}">Alterar senha</a></li>
            <li class="list-group-item"><a class="text-dark" href="{% url 'alterar_informacoes_da_conta_view' %}">Alterar informações da conta</a></li>
        </ul>
    </div>
</div>

{% endblock %}

locador/templates/views/devedores.html
{% extends 'base_locador.html' %}
{% block base_locador %}

<div class="card">
    <div class="card-header d-flex justify-content-between">
        <h5>Devedores deste mês</h5>
        <div>
            <input type="month" id="mes_referencia" class="form-control" onchange="window.location.href = `?mes_referencia=${this.value}`;" value="{{mes_referencia}}">
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive-lg">
            <table class="table mt-3 text-center table-hover">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Inquilino</th>
                        <th>Imovel</th>
                        <th>Valor</th>
                        <th>Data</th>
                        <th>Mudar status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pagamento in pagamentos %}
                    <tr>
                        <td>
                            {% if pagamento.status == 'N' %}
                                <span class="badge bg-danger">Aguardando</span>
                            {% elif pagamento.status == 'A' %}
                                <span class="badge bg-warning">Em análise</span>
                            {% elif pagamento.status == 'P' %}
                                <span class="badge bg-success">Pago</span>
                            {% endif %}
                        </td>
                        <td>{{pagamento.locatario}}</td>
                        <td>{{pagamento.imovel}}</td>
                        <td>{{pagamento.valor}}</td>
                        <td>{{pagamento.data|default_if_none:""}}</td>
                        <td>
                            {% if pagamento.status == 'N' or pagamento.status == 'A'  %}
                                <a href="{% url 'criar_pagamento_rapido_view' id_locatario=pagamento.locatario.id mes_referencia=mes_referencia %}" class="text-success">
                                    <i class="bi bi-currency-dollar"></i>
                                </a>
                            {% elif pagamento.status == 'P' %}
                                <a href="{% url 'deletar_pagamento_rapido_view' id_locatario=pagamento.id mes_referencia=mes_referencia %}" class="text-dark">
                                    <i class="bi bi-trash"></i>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>

{% endblock %}

locador/templates/views/home_locador.html
{% extends 'base_locador.html' %}
{% block base_locador %}

{% if not locador.data_nascimento_criacao %}
<div class="alert alert-warning">
    Atenção! Você não adicionou uma data de nascimento/criação. Ela é importante para recuperar a senha. Atualize seus dados nas <a href="">Configurações</a>
</div>
{% endif %}

<h1>home locador</h1>

<h2>{{user.first_name}} {{user.last_name}} </h2>

<a href="https://www.chartjs.org/docs/latest/charts/bar.html">https://www.chartjs.org/docs/latest/charts/bar.html</a>

<div>
    <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx = document.getElementById('myChart');
  
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
          label: '# of Votes',
          data: [12, 19, 3, 5, 2, 3],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>

{% endblock %}

locador/templates/views/inquilino_ao_imovel.html
{% extends 'base_locador.html' %}
{% block base_locador %}

<div class="col-sm-12 col-lg-6 offset-lg-3">
    <form method="POST">
        {% csrf_token %}
        <div class="card">
            <div class="card-header text-center">
                <h5>Adicionar inquilino ao imóvel</h5>
            </div>
            <div class="card-body">
                {% for field in form %}
                    <div class="form-floating mb-3">
                        {{field}}
                        {{field.label_tag}}
                        <span class="text-danger">{{field.errors.0}}</span>
                    </div>
                {% endfor%}
            </div>
            <div class="card-footer text-end">
                <a class="btn btn-light" href="{% url 'imoveis_locador_view' %}">Cancelar</a>
                <button type="submit" class="btn btn-orange">Salvar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

locador/templates/views/pagamentos_locador.html
{% extends 'base_locador.html' %}
{% block base_locador %}

<div class="row">
    <div class="col-sm-12 col-lg-6">
        <div class="accordion accordion-flush" id="accordionFlushLocador">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-pagamentoslocador" aria-expanded="false" aria-controls="flush-pagamentoslocador">
                        <h5>Pagamentos do locador (assinatura)</h5>
                    </button>
                </h2>
                <div id="flush-pagamentoslocador" class="accordion-collapse collapse" data-bs-parent="#accordionFlushLocador">
                    <div class="accordion-body">
                        {{pagamentos_locador}}
                    </div>
                </div>
            </div>            
        </div>
    </div>

    <div class="col-sm-12 col-lg-6">
        <div class="accordion accordion-flush" id="accordionFlushInquilinos">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-pagamentosinquilinos" aria-expanded="false" aria-controls="flush-pagamentosinquilinos">
                        <h5>Pagamentos dos inquilinos</h5>
                    </button>
                </h2>
                <div id="flush-pagamentosinquilinos" class="accordion-collapse collapse" data-bs-parent="#accordionFlushInquilinos">
                    <div class="accordion-body">
                        {{pagamentos_inquilinos}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}